name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: image-build-resources
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: jzeladmin2006/aircheck-frontend
